Vagrant.configure("2") do |config|
   config.vm.define "server" do |server|
		server.vm.box = "trusty64"
	   server.vm.provision :shell, :path => "server_bootstrap.sh"
		server.vm.network "private_network", type: "dhcp"
	end
   config.vm.define "client" do |client|
		client.vm.box = "trusty64"
	   client.vm.provision :shell, :path => "client_bootstrap.sh"
		client.vm.network "private_network", type: "dhcp"
	end
end
